### ISSUE TITLE
Problem with initial option settings

### ISSUE THREAD

**Issue by dongigi92** [cruikshj/knockout-select2#10]
Hi, i would to set initial settings like placeholder, etc in my select2.
I try to use the same code in your test files (in "lab" folder), but not work.
This is an example: http://jsbin.com/polazakeye/1/edit?html,js,output

Am I doing something wrong?

**Comment by cruikshj** [comment]
I have seen this before.  I will look into why the select2 option doesn't work, but for now, the optionsCaption knockout binding handler may work for you.

```
optionsCaption: 'My placeholder'
```

http://jsbin.com/rifunonuta/edit?html,js,output

**Comment by dongigi92** [comment]
Thanks for the answer. I thought that the placeholder wasn't the only options that not work. I used the optionsCaption for that and the js var for the other options.

HTML
`<select class="form-control select2" data-bind="options: vm.options, value: vm.selected, optionsText: 'text', optionsValue: 'id', optionsCaption: 'my placeholder', select2: vm.settings"></select>`

SCRIPT
`self.settings = {
          allowClear: true,
          maximumInputLength: 3
          // and others....
        };`
