### ISSUE TITLE
how to set initial values after select2 is called

### ISSUE THREAD

**Issue by dyardyGIT** [cruikshj/knockout-select2#3]
I am using 
$('#sel2').append("<option value='1234'>Dave</option>").trigger("change");

and am getting the following errors.

The select2('data') method was called on an element that is not using Select2.
Uncaught TypeError: Cannot read property 'data' of undefined

How do i set default values while using the bindinghandler?  If i try to set the value via the observable it is not reflected in the control.

i.e. say I want to set the initial value but i have setup using ajax and it is multiple.  The initial value is ignored and is not set in the 'data' property of the control.

ideas? (need help)

I have also tried
viewModel.approvers({id:'1234', text:'Dave'});  < while this does not error this value is not set in the controls data property, and the text 'Dave' is not visible in the control

**Comment by cruikshj** [comment]
You can use the options binding (and supporting bindings) built into knockout to accomplish this.  

I committed an example of using initial data with the ajax binding in the lab for you, but basically you provide 'options', 'selectedOptions', 'optionsValue' and 'optionsText' bindings in addition to the select2 binding. 'options' and 'selectedOptions' can be observable or not depending on your needs.

Again, see the example in the lab.

**Comment by dyardyGIT** [comment]
I did make some progress however i did have to modify the select2 binding handler...

I had to modify the following, i have commented out existing and see the 'add' section.

The reason...the binding handler set the select2Data observable to the value of 'data' when getting the data via json however when setting default options there wasn't a data property.  So, you can see if item.data===undefined (the case when setting default options) compared to when getting the data from ajax/via json.


 // Provide a hook for binding to the select2 "data" property; this property is read-only in select2 so not subscribing.
            if (ko.isWriteableObservable(allBindings[dataBindingName])) {
                dataChangeHandler = function () {
                    //commented out
                    //allBindings[dataBindingName]($(element).select2("data"));                    
                    
                    //added
                    var result = [];
                    var data = $(element).select2("data");
                    $.each(data, function (index, item) {
                        if (item.data === undefined) {
                            result.push({ DisplayName: item.text, Gen: item.id });
                        } else {
                            result.push({ DisplayName: item.data.text, Gen: item.data.id });
                        }
                    });
                    allBindings[dataBindingName](result);
                };
                $(element).on("change", dataChangeHandler);
            }

**Comment by cruikshj** [comment]
Did you try the setup from the example in the lab?
________________________________

**Comment by dyardyGIT** [comment]
I have been comparing your 'lab' code with mine and trying to find the differences.
As i just updated the issue i believe it is because I may be using observable results from ajax
The binding handler spec that i am using looks like (you can see the processResults below).


...            placeholder: placeHolder,            theme: "bootstrap",            ajax: {                url: personUrl,                method: 'POST',                data: function (params) {                    var optionsIn = { startsWith: params.term, finderFormat: lookupBy };                    var searchData = $.extend(defaults, optionsIn);                    return JSON.stringify(searchData);                                    },                dataType: 'json',                contentType: 'application/json',                delay: 1,                processResults: function (data, params) {                    var r = $.map(JSON.parse(data), function (item) {                                                return { id: item.Gen, text: item.DisplayName, data: item.Gen };                    });                    return {                        results: r                    };                }            },            multiple: true,            minimumInputLength: 3,            templateResult: function (item) {                return item.text;            },            templateSelection: function (item) {                return item.text;            } 
Date: Fri, 27 Nov 2015 17:32:37 -0800

**Comment by cruikshj** [comment]
the optionsValue and optionsText bindings support functions as well as strings, so you could use a function to get the observable display text and value.

```javascript
  optionsText: function(item) {
    return item.DisplayName();
  },
  optionsValue: function(item) {
    return item.Gen();
  }
```

**Comment by dyardyGIT** [comment]
In the scenario where we have initial options...
```  var initialOptions = [
                    { name: 'ALABAMA', abbreviation: 'AL' },
                    { name: 'ALASKA', abbreviation: 'AK' }
                ];```

they are not added to select2Data when the page/control loads so when sending select2Data back to the server they are missing the initial values

```
    <select multiple="multiple" data-bind="select2Data: select2Data, select2: spec, options: initialOptions, selectedOptions: initialSelectedOptions, optionsText: 'name', optionsValue: 'abbreviation'"></select>

    <br />
    <ul data-bind="foreach: select2Data">
        <li><span data-bind="text: text"></span></li>
    </ul>
```

Ideally in the above code I want to set select2Data: initialSelectedOptions as shown in the following but when i do this the initial values get overwritten in initialSelectedOptions when I pick a new item.

```<select multiple="multiple" data-bind="select2Data: initialSelectedOptions, select2: spec, options: initialOptions, selectedOptions: initialSelectedOptions, optionsText: 'name', optionsValue: 'abbreviation'"></select>
```

So, i want to append/update the values in initialSelectedOptions even when initial values exist.  Do you think this is possible?

**Comment by cruikshj** [comment]
It was indeed possible pre Select2v4.  Older versions of select2 had the "data" property as settable.  This is no longer the case in select2 v4.  The expectation, it seems, is that default values come from the select box itself, hence using the options binding as it will act against the underlying select element.

In you scenario, why not just initialize the data bound to select2Data yourself?  select2Data does honor the initial values and new values are added, so the problem, I assume is that if the user never changes your select2 element, the data you have bound is never set.  I recommend simply initializing that object as well to the initial options.

**Comment by dyardyGIT** [comment]
Agreed, I might have an answer/sample for above, however can you try this

In your sample in index.htm (for ajax) remove multiple='multiple' like

```<select data-bind="select2Data: select2Data, select2: spec, options: initialOptions, selectedOptions: initialSelectedOptions, optionsText: 'name', optionsValue: 'abbreviation'"></select>

Change initialOptions to 
```var initialOptions = [
                    { name: 'ALABAMA', abbreviation: 'AL' }
                ];```

I get the following errors in yours and mine as well ...

The select2('data') method was called on an element that is not using Select2.
Uncaught TypeError: Unable to process binding "options: function (){return initialOptions }"
Message: Cannot read property 'data' of undefined


I seem to have things working with when multiple='multiple' in the <select> tag however, when i want to make select2 use single values only by removing multiple in the select tag and setting a default option i get the above error. hmm

**Comment by dyardyGIT** [comment]
Stepping through code...without multiple='multiple', 
`allBindings[dataBindingName]($(element).select2("data"));`


is called before select2(bindingValue) and hence the error(s) above


whereas with multiple='multiple' 

```$(element).select2(bindingValue);``` 
is called first

**Comment by dyardyGIT** [comment]
Stepping through code...without multiple='multiple', 
`allBindings[dataBindingName]($(element).select2("data"));`


is called before select2(bindingValue) and hence the error(s) above


whereas with multiple='multiple' 

```$(element).select2(bindingValue);``` 
is called first

**Comment by dyardyGIT** [comment]
The following appears to work.

```
                    if ($(element).hasClass('select2-hidden-accessible'))
                        allBindings[dataBindingName]($(element).select2("data"));  
```
Checking to ensure that select2 is hooked up before calling allBindings seems to work. Is there a better way?

**Comment by cruikshj** [comment]
You are correct. I opened a bug for this #4

**Comment by cruikshj** [comment]
I used the following to ensure select2 is setup...

```
 dataChangeHandler = function() {
                    if (!$(element).data('select2')) return;                  
                    allBindings[dataBindingName]($(element).select2('data'));
                };
```

**Comment by cruikshj** [comment]
I will package up a release of the fix later today, if all goes well.
